### ISSUE TITLE
kamek

### ISSUE THREAD

**Issue by kameko** [rein/Monado#1]
help i want to port this to JAVA how can i install javm

**Comment by 2-3** [comment]
help how did I get here

**Comment by kameko** [comment]
![Image](http://www.hnng.moe/f/2hA)

**Comment by kameko** [comment]
FUCK YOU ROSE
FUCK
YOU
ROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSE

**Comment by kameko** [comment]
FUCK

**Comment by kameko** [comment]
![Image of MAD](http://img.bleacherreport.net/img/images/photos/001/533/190/john-cena-intense1_original_crop_340x234_original_crop_north.jpg?w=337&h=225&q=75)

**Comment by kameko** [comment]
MAAAAAAAAAAAD
